[package]
name = "guild-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.143"
serenity = "0.12.4"
tokio = {version="1.47.1", features=["full"]}
